### ISSUE TITLE
No firmware download start, when trying to save the battery

### ISSUE THREAD

**Issue by Roger53** [mysensors/MySensorsBootloaderRF24#10]
Hi, love your MYSbootloader/Controller effort,

My sensors reports every 2 minutes, using "smartSleep", marked it as running on battery, and I can indeed download new firmware, great. I see my data and a heartbeat in MYScontroller every 2 minutes

This works very good (but only after adding the famous both 0.1 and 10 uF capacitors to the NRF)

But the "smartSleep" adds 0.5 second radio/MCU on time and that is killing the battery : 
(0.5 sec * 20mA * 30 times per hour /3600)*24*365 = 730mAh right ? 
So if I am correct, that .5 second every 2 minutes alone will empty an AA battery in 1 year

So as alternative : 
I report every 2 minutes and then a "sleep", but every 30 times = 1 hour, I throw in a "smartSleep" and not a "sleep". I see my data every 2 minutes and I see a heartbeat every 30 times = 1 hour

I don't mind if it can take 1 hour, but I don't want to manually reset/power cycle, as the sensors are on difficult places so battery exchange and reset should be limited :-)

Problem : 
But when I request a firmware download, it does not start on the "smartSleep"/heartbeat
Perhaps you ignore the firmware download when you have seen a "sleep" or it takes too long or  ??
I did not manage to find the source of the MYSController, did you make that available ?

In a test I lowered the sleep time to 10 seconds, so 5 minutes for a heartbeat , same problem.

Reset and power cycle do start a download, so no major issues there.

Can you change is so that it will start the download on any first "smartSleep" for below ( battery saving script)? Lets say even if 24 hours :-)

void loop()     
 {
  BatteryVoltage = readVcc() * BatteryCorrection ; // readVcc returns a long type
  send(msgBatt.set  (BatteryVoltage, 2));
  if (count == 0)
   {
    smartSleep(SleepTime);
   }
  else
   {
    sleep(SleepTime);      
   }
 count = (count + 1) % 30;
}

**Comment by tekka007** [comment]
@Roger53 Yes, you are right - MYSController does not trigger on a specific (=heartbeat) message for battery-powered sensors. I've refactored the smartSleep implementation (MySensors PR #722) with two new message types:
- sent before smart-sleeping:` I_PRE_SLEEP_NOTIFICATION`, payload: processing time in MS before sleeping
- sent after smart-sleeping: `I_POST_SLEEP_NOTIFICATION`, payload: sleeping time in MS

These changes will be implemented in the next release of MYSController and used as trigger to release retained msgs.

**Comment by Roger53** [comment]
Thanks Tekka007
(Missed your very quick reply)

Still I am surprised that when I always use normal smartsleep, I manage to get the download working, so I got the feeling as if we are almost there. but ok, you are the specialist :-).

So that needs an update in
   MySensors lib (now 2.1.1) in Arduino IDE and 
   MySController (now 1.0.0beta: b3314:)
right ?

Any idea on planning of both ?

Do I also have to update that blootloader ( would need some soldering on a few devices :-) )

( Not pushing, just eagerly asking :-) )

 👍
