### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sindrehal** [mysensors/MySensorsBootloaderRF24#14]
Hi. I have tried the hex file for 328p 16mhz. When i power on i se an ID request on the gateway, but doesnt register with the Controller. When i use the MYSBootloader included with the latest MYSController the node registers and OTA works just fine. I use mycontroller.org and RasPI as gateway. Anyone got this bootloader working? Or can give me some tips on getting it to work?
Regrds
Sindre

**Comment by Akubi** [comment]
Hi, can you test using MYSController in "GW mode" ?
Disable "Auto ID" on MYSController, connect mycontroller.org to MYSController and observe the messages on MYSController Debug Window.

**Comment by tekka007** [comment]
Closed due to inactivity
