### ISSUE TITLE
Why would firmware-less node proceed to startup after MAX_FIRMWARE_REQUEST_RESEND reached?

### ISSUE THREAD

**Issue by gnalbandian** [mysensors/MySensorsBootloaderRF24#15]
Hi @tekka007,

I was wondering why a node that I left last night without firmware stopped asking for it(firmware), this morning. 
I read the code and found what's causing it.
Is this the intended behavior?

Wouldn't be nicer to have the node requesting firmware perpetually until firmware submitted?

Now, that node is in limbo state, without firmware, and there is no other way to restore communication with it, than with a hardware reset.

Let me know what you think, i can contribute with coding.

Regards.

**Comment by tekka007** [comment]
@gnalbandian Normally, the node won't exit the bootloader and re-request a FW unless the CRC check passes (see [here](https://github.com/mysensors/MySensorsBootloaderRF24/blob/development/MySensorsBootloader.h#L317)) - difficult to say what happened in your case.

**Comment by gnalbandian** [comment]
Ok @tekka007, I'll close the issue until further investigation or if the issues happens again
