### ISSUE TITLE
OTA infinit loop

### ISSUE THREAD

**Issue by castorinop** [mysensors/MySensorsBootloaderRF24#17]
in some times, the bootloader keeps request a firmware request and aparently dont listen the response from gateway. 

```
2903	09/07/2017 12:52:52	RX	3	INTERNAL	C_STREAM	NO	ST_FIRMWARE_REQUEST	28000100F303
2904	09/07/2017 12:52:52	TX	3	INTERNAL	C_STREAM	NO	ST_FIRMWARE_RESPONSE	28000100F3039C048CEE96E00E94401F8BEC96E00E94
2907	09/07/2017 12:52:56	RX	3	INTERNAL	C_STREAM	NO	ST_FIRMWARE_REQUEST	28000100F203
2908	09/07/2017 12:52:56	TX	3	INTERNAL	C_STREAM	NO	ST_FIRMWARE_RESPONSE	28000100F20396041092990410929A0410929B041092
2911	09/07/2017 12:52:59	RX	3	INTERNAL	C_STREAM	NO	ST_FIRMWARE_REQUEST	28000100F103
2912	09/07/2017 12:52:59	TX	3	INTERNAL	C_STREAM	NO	ST_FIRMWARE_RESPONSE	28000100F10395048093940486EC90E0909397048093
```

**Comment by tekka007** [comment]
@castorinop this could possibly hint to a power/interference issue with your GW. What is your GW setup (cap on radio?) and distance between GW and node?

**Comment by castorinop** [comment]
After loop i try hard reset the node. and when boot try request again ST_FIRMWARE_REQUEST 28000100F303.

node: power 12v 1A, radio with cap
gateway: arduino uno serial (115200bps) powered via usb + radio with cap
distance: 4m

**Comment by tekka007** [comment]
How did you flash the bootloader - what settings did you use?

**Comment by castorinop** [comment]
I use Arduino as ISP
![wired](https://www.arduino.cc/en/uploads/Tutorial/BreadboardAVR.png)

boards.txt
```
MYSBL.name=ATmega328 16Mhz MYSBootloader

MYSBL.upload.tool=avrdude
MYSBL.upload.protocol=arduino
MYSBL.upload.maximum_size=30720
MYSBL.upload.maximum_data_size=2048
MYSBL.upload.speed=115200

MYSBL.bootloader.tool=avrdude
MYSBL.bootloader.low_fuses=0xF7
MYSBL.bootloader.high_fuses=0xDA
MYSBL.bootloader.extended_fuses=0x06
MYSBL.bootloader.unlock_bits=0x3F
MYSBL.bootloader.lock_bits=0x0F
MYSBL.bootloader.file=MySensors/MYSBootloader_16Mhz.hex

MYSBL.build.mcu=atmega328p
MYSBL.build.f_cpu=16000000L
MYSBL.build.board=AVR_UNO 
MYSBL.build.core=arduino
MYSBL.build.variant=standard
```

**Comment by castorinop** [comment]
can be that ST_FIRMWARE_REQUEST is decreasing ?

**Comment by Akubi** [comment]
Hi @castorinop,

What is exactly the problem ?
Bootloader will ask for firmware block by block.
So yes the block address is decreasing.
It seams that your node is just asking for the firmware.
The timings are strange. The bootloader normaly ask for a new block very fast.
Can you plese describe a little better your setup ?
Radio model, cabling, bootloader version ...
I had some upload speed problems with PA radios, bad cabling and old bootloader version.

**Comment by castorinop** [comment]
I update via ota several times with another node (same config) and there was no problem. 
reupload sketch via USB on problematic node, test upload via ota a couple of times and work very well (very fast, ~ 2 mins).

**Comment by castorinop** [comment]
@Akubi 
nodes: 
- radios: nfr24l01+ with 10uf cap attached at power pins wired to arduino uno like mysensors tutorial.
- bootloader: 1.3 pre 3

gateway: 
- radios: nfr24l01+ with 10uf cap attached at power pins wired to arduino uno like mysensors tutorial.
- bootloader: arduino
- firmware: mysensors  GatewaySerial

**Comment by Akubi** [comment]
@castorinop

Ok 
     

- For Bootloader, check if you are using last dev version (some timing changes 1 week ago)
- Check again radio cabling (soldering on CE, CNS)
- Check again radio power supply level
- Check again radio GND
 

nRF24 modules are 3.3v powered. SPI pins are 5v tolerant, but if GND is not well done SPI timings can be altered using 5V Arduino.

I personally solved this kind of problems on 16MHz, 5V Arduino and **Clone PA nRF24** by last release of Bootloader and using twisted pair cable for radio connection.

Hope that can help
