### ISSUE TITLE
Question: What are correct boards.txt info/fuses for 1mhz version?

### ISSUE THREAD

**Issue by dakipro** [mysensors/MySensorsBootloaderRF24#18]
Hi, I guess it is not yet ready, but maybe it is a "quick&easy" for someone to post correct content of boards.txt for 1mhz (3.3v) version of bootloader?
Thanks

**Comment by xydix** [comment]
I wonder the same. Can't upload anything (serial) to the board when burnt the 1mhz bootloader.
BTW i have problems with the newest version av the 8mhz too.
The one before the latest works but not the latest.
Would be nice with solid info what to put in boards.txy for pro mini.

**Comment by Akubi** [comment]
Hi, personally I only use Pro Mini (3.3V, 8MHz) and use de standard boards definition.
No special definitions for MySensorsBootloaderRF24.

In fact that depend on options used by @tekka007 to compile.

I personally compile with fallowing options :

For 1MHz : CLK=1000000L BAUDRATE=9600
For 8MHz : CLK=8000000L BAUDRATE=57600
For 16MHz : CLK=16000000L BAUDRATE=57600

@tekka007 Can you please publish the used compilation options ?

```
## Arduino Pro or Pro Mini (3.3V, 8 MHz) w/ ATmega328
## --------------------------------------------------
pro.menu.cpu.8MHzatmega328=ATmega328 (3.3V, 8 MHz)

pro.menu.cpu.8MHzatmega328.upload.maximum_size=30720
pro.menu.cpu.8MHzatmega328.upload.maximum_data_size=2048
pro.menu.cpu.8MHzatmega328.upload.speed=57600

pro.menu.cpu.8MHzatmega328.bootloader.low_fuses=0xFF
pro.menu.cpu.8MHzatmega328.bootloader.high_fuses=0xDA
pro.menu.cpu.8MHzatmega328.bootloader.extended_fuses=0x05
pro.menu.cpu.8MHzatmega328.bootloader.file=atmega/ATmegaBOOT_168_atmega328_pro_8MHz.hex

pro.menu.cpu.8MHzatmega328.build.mcu=atmega328p
pro.menu.cpu.8MHzatmega328.build.f_cpu=8000000L
```

**Comment by tekka007** [comment]
Updated, see https://github.com/mysensors/MySensorsBootloaderRF24/commit/62d621c2f410c071a075ac06e6bce85a898081ad
