### ISSUE TITLE
How to change time while bootloader is looking for new firmware?

### ISSUE THREAD

**Issue by jkoenig72** [mysensors/MySensorsBootloaderRF24#23]
Hi, 

1st - great work. Love it.

Just wondering how I can minimize the boot time, while its looking for a new firmware?

Regards
Joerg

**Comment by jkoenig72** [comment]
I mean the ST_FIRMWARE_CONFIG_REQUEST - can that time be minimized?

**Comment by tekka007** [comment]
@jkoenig72 Yes, MYSController with AutoFW enabled (this will "acknowledge" the node's FW and proceed to sketch startup) or via reducing the overall waiting time [here](https://github.com/mysensors/MySensorsBootloaderRF24/blob/development/MySensorsBootloader.h#L99) (be careful when changing this value)
