### ISSUE TITLE
Tired lastest hex files, verification error

### ISSUE THREAD

**Issue by xydix** [mysensors/MySensorsBootloaderRF24#28]
Just downloaded the latest files from dev branch.
Copied boards from here.
When i try to upload any mysensorsBootloader i get:
avrdude: verification error, first mismatch at byte 0x7800
         0x00 != 0x11
avrdude: verification error; content mismatch

**Comment by tekka007** [comment]
Looks like you're having issues with avrdude or your hardware - this error message is not related to MYSBootloader.

**Comment by xydix** [comment]
Okay. Strange. I replaced the hex files with older mysbootloader-hex files and it worked on first try.

**Comment by tekka007** [comment]
Then the avrdude flashing process is not working and/or you hardware is damaged or write-protected. Can you flash any other, i.e. optiboot bootloader?

**Comment by xydix** [comment]
Don't have any optiboot right now to try with. I think i bricked my first arduino board so i tried a new. Then i worked. Can the arduino be write protected or do you think my programmer is broken? It's a USBasp clone

**Comment by tekka007** [comment]
This depends on the fuse/lock bit settings (https://forum.arduino.cc/index.php?topic=374842.0) -  Optiboot: https://github.com/Optiboot/optiboot

**Comment by xydix** [comment]
Sorry for being a super noob. But isn't the fusees set by the info in boards.txt?

**Comment by tekka007** [comment]
sure - so you didn't change the settings in boards.txt? Can you post the avrdude output here?

**Comment by xydix** [comment]
I copied the text from boards here and pasted it in my boards.txt
I, right now, tried it again with the lastest hex-files. I worked. =)
Don't know if something was wrong with my other board... It's bricked now anyway =)

**Comment by tekka007** [comment]
ok - so we can close this issue as it turns out to be hardware/wiring related?

**Comment by xydix** [comment]
Probably hardware. The wiring was correct ;-)
Thank you for a great bootloader and your quick reply.

**Comment by tekka007** [comment]
Thanks for your feedback. Have fun :)
