### ISSUE TITLE
Flash init error

### ISSUE THREAD

**Issue by danielefrigo** [mysensors/MySensorsBootloaderRF24#30]
I have freshly created pro mini 3.3 8 MHz.
I flashed MySbootloader (developer branch) and when I try on OTA update I always get:
!OTA:FWP:FLASH INIT FAIL

**Comment by tekka007** [comment]
MYSBootloader is a offline OTA update solution and does not require external flash chips (see https://www.mysensors.org/about/fota for instructions) - in short, you have to comment ```#define MY_OTA_FIRMWARE_FEATURE```
