### ISSUE TITLE
Compiling the bootloader - Not bootloader working beside the precompiled ones

### ISSUE THREAD

**Issue by anisghaoui** [mysensors/MySensorsBootloaderRF24#37]
Hello,

I have tried to compile your source by using the make file.

No matter what i tried i can't get a bootloader that i compiled myself  to work correctly. Only those precompiled that you publish work.
The bootloader is usually too big , it goes beyond address 8000 , I notice that the make file puts the bootloader at 0x7800.
`-section-start=.text=0x7800`

More information: 
-Win 10
-using AVRWIN ( paths are correct in the make file)

The make result : 
`$ make
rm *.o
rm *.elf
rm *.hex
"C:/WinAVR-20100110/bin/avr-gcc" -funsigned-char -funsigned-bitfields -DF_CPU=16000000L -Os -ffunction-sections -fdata-sections -fpack-struct -fshort-enums -mrelax -Wall -Wextra -Wundef -pedantic -mmcu=atmega328p -c -std=gnu99 -MD -MP -MF "MYSBootloader.d" -MT"MYSBootloader.d" -MT"MYSBootloader.o"  -IC:/WinAVR-20100110/avr/include/avr/ MYSBootloader.c -o MYSBootloader.o `
`In file included from Core.h:40,`
`from MYSBootloader.c:69:`
`HW.h:51:2: warning: #warning is a GCC extension`
`HW.h:51:2: warning: #warning BAUD_RATE error greater than 2%`
`In file included from Core.h:42,`
`from MYSBootloader.c:69:`
`MyMessage.h:292: warning: ISO C doesn't support unnamed structs/unions`
`"C:/WinAVR-20100110/bin/avr-gcc" -nostartfiles -Wl,-s -Wl,-static -Wl,-Map=".map" -Wl,--start-group -Wl,--end-group -Wl,--gc-sections -mrelax -Wl,-section-start=.text=0x7800 -mmcu=atmega328p   -o MYSBootloader.elf MYSBootloader.o -lm
"C:/WinAVR-20100110/bin/avr-objcopy" -O ihex -R .eeprom MYSBootloader.elf MYSBootloader.hex`
`"C:/WinAVR-20100110/bin/avr-size" MYSBootloader.elf`
`text    data     bss     dec     hex filename`
`2386       6      72    2464     9a0 MYSBootloader.elf`

If helping me compile this isn't easy, but you could somehow compile a bootloader for me with adding two lines : 

`DDRD |= 0x80;
PORTD |= 0x80;`

after line 100 in MYSbootloader.c.

Thank you for your time

**Comment by anisghaoui** [comment]
Solved, Just Install Atmel Studio and edit the PATH in the Make file.

Different compiler versions/optimizations.

**Comment by tekka007** [comment]
@anisghaoui Thanks for the feedback. Have fun!
