### ISSUE TITLE
compiling for CE pin 7, CSN pin 8

### ISSUE THREAD

**Issue by acejoh** [mysensors/MySensorsBootloaderRF24#38]
Hi,

I'm migrating from RF24Network to MySensors. My config used to be CE7, CSN8. I'm trying to build the bootloader for this configuration, but I can't get it to work.
Using a new node with the default pin config of CE9, CSN10 does work, but I'd prefer not to rewire my existing nodes if I can help it.

I added a new define to MYSbootloader.c and the following code to HW.h:

#elif defined(SPI_PINS_CE7_CSN8)
	#define CE_PORT		PORTD	// port for CE
	#define CE_DDR		DDRD	// DDR for CE
	#define	CE_PIN		PD7		// Arduino Pin 7 <-> Bit 7 of port D

	#define CSN_PORT	PORTB	// port for CSN
	#define CSN_DDR		DDRB	// DDR for CSN
	#define	CSN_PIN		PB0		// Arduino Pin  8 <-> Bit 2 of port B
#endif

...

	#elif defined(SPI_PINS_CE7_CSN8)
		// PB0 is SS pin has to be defined as OUTPUT, else SPI goes to slave mode
		SPI_DDR = _BV(SPI_MOSI) | _BV(SPI_SCLK) | _BV(PB0) | _BV(CSN_PIN);
		CE_DDR = _BV(CE_PIN);
	#endif

based on what I found for the existing defines. It's the last part I'm not sure about. Could anyone help me out?
Thanks!

**Comment by tekka007** [comment]
PB2 has to be defined as OUTPUT, the rest looks ok, i.e.

```
#elif defined(SPI_PINS_CE7_CSN8)
	// PB2 has to be defined as OUTPUT, else SPI goes to slave mode
	SPI_DDR = _BV(SPI_MOSI) | _BV(SPI_SCLK) | _BV(PB2) | _BV(CSN_PIN);
	CE_DDR = _BV(CE_PIN);
#endif
```

**Comment by acejoh** [comment]
Thanks for your prompt response! I have made the change but unfortunately this config does not work either. I'm getting two brief LED flashes in quick succession at regular intervals (every couple of seconds) and no messages are received by the gateway. 
Do you know what this could mean?

**Comment by acejoh** [comment]
I finally found the problem: the make clean wasn't working (probably need to run as administrator) so I was manually deleting the .hex file each time I ran make, without realizing that I also needed to delete the .o and .elf files! Once I deleted those files and ran make with the configuration you gave me it worked!
