### ISSUE TITLE
FW update problem  with ESP8266 gateway 

### ISSUE THREAD

**Issue by MiKa1975** [mysensors/MySensorsBootloaderRF24#4]
I have problem with FW update via MYSController, node just rebooting and thats all - no code update

**Comment by tekka007** [comment]
@MiKa1975 Please describe your setup, post the full debug from MYSController and add any other information that may be help to nail down the issue.

**Comment by MiKa1975** [comment]
Hi,
here is the log from MYScontroller
I testing two nodes and one WiFi gateway with ESP8266 connected to Domoticz
Everything working fine just FW update not

8.1.2017 19:29:51	RX	30;255;0;0;17;2.2.0-beta
8.1.2017 19:29:51	TX	30;255;3;0;6;M
8.1.2017 19:29:51	RX	30;255;3;0;6;0
8.1.2017 19:29:51	RX	30;255;3;0;11;Door/Window Sensor+ SI702
8.1.2017 19:29:51	RX	30;255;3;0;12;1.0
8.1.2017 19:29:51	DEBUG	Update child id=3, type=DOOR
8.1.2017 19:29:51	RX	30;3;0;0;0;
8.1.2017 19:29:51	DEBUG	Update child id=8, type=DOOR
8.1.2017 19:29:51	RX	30;8;0;0;0;
8.1.2017 19:29:52	CHILD	New child discovered, node id=30, child id=7
8.1.2017 19:29:52	DEBUG	Update child id=7, type=HUM
8.1.2017 19:29:52	RX	30;7;0;0;7;
8.1.2017 19:29:55	INFO	FW "MiKa" assigned to node 30
8.1.2017 19:29:57	TX	30;0;3;0;13;0
8.1.2017 19:30:00	RX	0;255;3;0;22;714327051
8.1.2017 19:30:04	CHILD	New child discovered, node id=30, child id=internal
8.1.2017 19:30:04	DEBUG	Update child id=255, type=ARDUINO_NODE
8.1.2017 19:30:04	RX	30;255;0;0;17;2.2.0-beta
8.1.2017 19:30:05	TX	30;255;3;0;6;M
8.1.2017 19:30:05	RX	30;255;3;0;6;0
8.1.2017 19:30:05	RX	30;255;3;0;11;Door/Window Sensor+ SI702
8.1.2017 19:30:05	RX	30;255;3;0;12;1.0
8.1.2017 19:30:05	CHILD	New child discovered, node id=30, child id=3
8.1.2017 19:30:05	DEBUG	Update child id=3, type=DOOR
8.1.2017 19:30:05	RX	30;3;0;0;0;
8.1.2017 19:30:05	CHILD	New child discovered, node id=30, child id=8
8.1.2017 19:30:05	DEBUG	Update child id=8, type=DOOR
8.1.2017 19:30:05	RX	30;8;0;0;0;
8.1.2017 19:30:10	RX	0;255;3;0;22;714336988

**Comment by tekka007** [comment]
Can you upload the sketch? Your node does not seem to process incoming messages. Please also add the debug log obtained from the node.

**Comment by MiKa1975** [comment]
simplest version :)

****************************************************************
MYSController debug log:
8.1.2017 19:43:01	RX	0;255;3;0;22;715097151
8.1.2017 19:43:04	DEBUG	Update child id=255, type=ARDUINO_RELAY
8.1.2017 19:43:04	RX	3;255;0;0;18;2.2.0-beta
8.1.2017 19:43:04	TX	3;255;3;0;6;M
8.1.2017 19:43:04	RX	3;255;3;0;6;0
8.1.2017 19:43:04	RX	3;255;3;0;11;Repeater Node
8.1.2017 19:43:04	RX	3;255;3;0;12;1.0
8.1.2017 19:43:07	INFO	FW "MiKa" assigned to node 3
8.1.2017 19:43:08	TX	3;0;3;0;13;0
8.1.2017 19:43:11	CHILD	New child discovered, node id=3, child id=internal
8.1.2017 19:43:11	DEBUG	Update child id=255, type=ARDUINO_RELAY
8.1.2017 19:43:11	RX	3;255;0;0;18;2.2.0-beta
8.1.2017 19:43:12	TX	3;255;3;0;6;M
8.1.2017 19:43:12	RX	3;255;3;0;6;0
8.1.2017 19:43:12	RX	0;255;3;0;22;715107494
8.1.2017 19:43:12	RX	3;255;3;0;11;Repeater Node
8.1.2017 19:43:12	RX	3;255;3;0;12;1.0
8.1.2017 19:43:21	RX	0;255;3;0;22;715117171
****************************************************************
Sketch:

 DESCRIPTION
 * Example sketch showing how to create a node thay repeates messages
 * from nodes far from gateway back to gateway.
 * It is important that nodes that has enabled repeater mode calls
 * process() frequently. Repeaters should never sleep.
 */

// Enable debug prints to serial monitor
#define MY_DEBUG

// Enable and select radio type attached
#define MY_RADIO_NRF24
//#define MY_RADIO_RFM69
#define MY_NODE_ID 3
#define MY_RF24_CE_PIN A3    // Radio specific settings for RF24
#define MY_RF24_CS_PIN A2   // Radio specific settings for RF24 

// Enabled repeater feature for this node
#define MY_REPEATER_FEATURE

#include <MySensors.h>

void setup()
{

}

void presentation()
{
	//Send the sensor node sketch version information to the gateway
	sendSketchInfo("Repeater Node", "1.0");
}

void loop()
{
}

****************************************************************
Node log:
0 MCO:BGN:INIT REPEATER,CP=RNNRA--,VER=2.2.0-beta
4 TSM:INIT
6 TSF:WUR:MS=0
12 TSM:INIT:TSP OK
14 TSM:INIT:STATID=3
16 TSF:SID:OK,ID=3
18 TSM:FPAR
55 TSF:MSG:SEND,3-3-255-255,s=255,c=3,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
638 TSF:MSG:READ,0-0-3,s=255,c=3,t=8,pt=1,l=1,sg=0:0
645 TSF:MSG:FPAR OK,ID=0,D=1
2062 TSM:FPAR:OK
2062 TSM:ID
2064 TSM:ID:OK
2066 TSM:UPL
2070 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=24,pt=1,l=1,sg=0,ft=0,st=OK:1
2084 TSF:MSG:READ,0-0-3,s=255,c=3,t=25,pt=1,l=1,sg=0:1
2091 TSF:MSG:PONG RECV,HP=1
2093 TSM:UPL:OK
2095 TSM:READY:ID=3,PAR=0,DIS=1
2101 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=15,pt=6,l=2,sg=0,ft=0,st=OK:0100
2109 TSF:MSG:READ,0-0-3,s=255,c=3,t=15,pt=6,l=2,sg=0:0100
2117 TSF:MSG:SEND,3-3-0-0,s=255,c=0,t=18,pt=0,l=10,sg=0,ft=0,st=OK:2.2.0-beta
2127 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=6,pt=1,l=1,sg=0,ft=0,st=OK:0
2367 TSF:MSG:READ,0-0-3,s=255,c=3,t=6,pt=0,l=1,sg=0:M
2377 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=11,pt=0,l=13,sg=0,ft=0,st=OK:Repeater Node
2390 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=12,pt=0,l=3,sg=0,ft=0,st=OK:1.0
2398 MCO:REG:REQ
2400 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=26,pt=1,l=1,sg=0,ft=0,st=OK:2
2772 TSF:MSG:READ,0-0-3,s=255,c=3,t=27,pt=1,l=1,sg=0:1
2779 MCO:PIM:NODE REG=1
2781 MCO:BGN:STP
2783 MCO:BGN:INIT OK,TSP=1
2969 TSF:MSG:READ,0-0-3,s=255,c=3,t=6,pt=0,l=1,sg=0:M
7163 TSF:MSG:READ,0-0-3,s=0,c=3,t=13,pt=0,l=1,sg=0:0
0 MCO:BGN:INIT REPEATER,CP=RNNRA--,VER=2.2.0-beta
4 TSM:INIT
6 TSF:WUR:MS=0
12 TSM:INIT:TSP OK
14 TSM:INIT:STATID=3
16 TSF:SID:OK,ID=3
18 TSM:FPAR
55 TSF:MSG:SEND,3-3-255-255,s=255,c=3,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
94 TSF:MSG:READ,0-0-3,s=255,c=3,t=8,pt=1,l=1,sg=0:0
100 TSF:MSG:FPAR OK,ID=0,D=1
2062 TSM:FPAR:OK
2062 TSM:ID
2064 TSM:ID:OK
2066 TSM:UPL
2070 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=24,pt=1,l=1,sg=0,ft=0,st=OK:1
2084 TSF:MSG:READ,0-0-3,s=255,c=3,t=25,pt=1,l=1,sg=0:1
2091 TSF:MSG:PONG RECV,HP=1
2093 TSM:UPL:OK
2095 TSM:READY:ID=3,PAR=0,DIS=1
2101 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=15,pt=6,l=2,sg=0,ft=0,st=OK:0100
2107 TSF:MSG:READ,0-0-3,s=255,c=3,t=15,pt=6,l=2,sg=0:0100
2117 TSF:MSG:SEND,3-3-0-0,s=255,c=0,t=18,pt=0,l=10,sg=0,ft=0,st=OK:2.2.0-beta
2127 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=6,pt=1,l=1,sg=0,ft=0,st=OK:0
2678 TSF:MSG:READ,0-0-3,s=255,c=3,t=6,pt=0,l=1,sg=0:M
2686 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=11,pt=0,l=13,sg=0,ft=0,st=OK:Repeater Node
2699 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=12,pt=0,l=3,sg=0,ft=0,st=OK:1.0
2705 MCO:REG:REQ
2709 TSF:MSG:SEND,3-3-0-0,s=255,c=3,t=26,pt=1,l=1,sg=0,ft=0,st=OK:2
3145 TSF:MSG:READ,0-0-3,s=255,c=3,t=27,pt=1,l=1,sg=0:1
3151 MCO:PIM:NODE REG=1
3155 MCO:BGN:STP
3158 MCO:BGN:INIT OK,TSP=1
3160 TSF:MSG:READ,0-0-3,s=255,c=3,t=6,pt=0,l=1,sg=0:M

****************************************************************

**Comment by tekka007** [comment]
Ok, there are no MYSBootloader init messages shown in the log - how did you flash the bootloader?

**Comment by MiKa1975** [comment]
USBasp, latest version of mysbootloader

**Comment by tekka007** [comment]
Apparently something went wrong there - bootloader doesn't kick in.

**Comment by tekka007** [comment]
I assume you are on channel 76 - if so, please re-download the .hex file (updated) or re-build the bootloader. The previous one could have been on channel 84.

**Comment by MiKa1975** [comment]
done, but result is the same

**Comment by tekka007** [comment]
Strange - I just successfully verified your setup here. Can you post the debug log from flashing the bootloader with USBasp?

**Comment by MiKa1975** [comment]
Problem solved, I have attached NRF on diffewrent pins for CE and CSN on my development board, after modifiyng of MYSBootloader.c and HW.h working without problem.
Thanks!

**Comment by tekka007** [comment]
Perfect, thanks for your feedback. Have fun!
