### ISSUE TITLE
hex file for other frequencies

### ISSUE THREAD

**Issue by vzorglub** [mysensors/MySensorsBootloaderRF24#9]
Hello,
Would you be able to publish ex files for 8Mhz and 1Mhz? Especially the 1Mhz as it is the frequency most used for battery devices. Thanks

**Comment by jkandasa** [comment]
@tekka007 Yes, kindly compile and update hex files for all the major frequencies. `1MHz`, `8MHz` and `16MHz`.

I tried to compile current development version for 8 MHz and it is not working. I do not know what was the issue. Curently I am using 8 MHz from here >> https://forum.mysensors.org/topic/4991/mysbootloader-1-3pre2-testing which is working perfectly.

**Comment by tekka007** [comment]
see #11

**Comment by jkandasa** [comment]
@tekka007 Thank you so much!!

**Comment by shajek** [comment]
Can you add even 4Mhz version? It's compromise between low power (run on 1.8V) and speed :) thank you
